# Configures this workflow to run every time a change is pushed to the branch called `main`.
name: deploy_images
on:
  push:
    branches: ['main']

# Defines custom environment variables for the workflow.
env:
  REGISTRY: ghcr.io

# Defines a job to build and push Docker images.
jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_type: ['hip-linux-anvil-cos7', 'hip-linux-anvil-cuda-11.2']
    permissions:
      contents: read
      packages: write
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
          remove-codeql: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ${{ matrix.image_type }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ matrix.image_type }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
